### ISSUE TITLE
No module named lib.settings (launcher.tac)

### ISSUE THREAD

**Issue by maulerjan** [moopless/stratum-mining-litecoin#49]
Hi, 

I'm trying to execute this command: "twistd -ny launcher.tac -l log/debug.log"

But I'm still receiving error:

"
  File "launcher.tac", line 14, in <module>
    import lib.settings as settings
exceptions.ImportError: No module named lib.settings

Failed to load application: No module named lib.settings
"

I will cry soon...

**Comment by moopless** [comment]
lib.settings is a local library (stratum-mining-litecoin/lib/settings.py) Please make sure it exists. Check to make sure the path is correct at the top of launcher.tac. It is also likely that stratum core is not installed.

**Comment by moopless** [comment]
Any update on this?

**Comment by maulerjan** [comment]
Still the same error. :-( I istall Stratum core, and do all stuffs exactly same like in INSTALL.md is described, but when i try to "twistd -ny launcher.tac -l log/debug.log", same error. Directory "lib" and file "settings.py" inside exists, but I don't see any path at the top of launcher.tac

**Comment by moopless** [comment]
Can you upload the debug.log and stratum.log to pastebin? Make sure to comment out any private information if DEBUG=true is enabled.

**Comment by moopless** [comment]
Any Update on this?

**Comment by tbourvon** [comment]
Same error here, the debug.log file doesn't even get created, neither does stratum.log.
It simply seems that the launcher doesn't have "lib/" in its import path or something similar.
I am not very familiar with Python.

**Comment by nicoschtein** [comment]
Just use https://github.com/ahmedbodi/stratum-mining

2013/12/31 BurningMind notifications@github.com

**Comment by EvgenijM86** [comment]
I've got same error with ahmedbodi/stratum-mining.

**Comment by majeed703** [comment]
Same error getting . Please help me to fix this essue

Unhandled Error
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/Twisted-16.7.0rc2-py2.7-linux-x86_64.egg/twisted/application/app.py", line 648, in run
runApp(config)
File "/usr/local/lib/python2.7/dist-packages/Twisted-16.7.0rc2-py2.7-linux-x86_64.egg/twisted/scripts/twistd.py", line 25, in runApp
_SomeApplicationRunner(config).run()
File "/usr/local/lib/python2.7/dist-packages/Twisted-16.7.0rc2-py2.7-linux-x86_64.egg/twisted/application/app.py", line 379, in run
self.application = self.createOrGetApplication()
File "/usr/local/lib/python2.7/dist-packages/Twisted-16.7.0rc2-py2.7-linux-x86_64.egg/twisted/application/app.py", line 444, in createOrGetApplication
application = getApplication(self.config, passphrase)
--- ---
File "/usr/local/lib/python2.7/dist-packages/Twisted-16.7.0rc2-py2.7-linux-x86_64.egg/twisted/application/app.py", line 455, in getApplication
application = service.loadApplication(filename, style, passphrase)
File "/usr/local/lib/python2.7/dist-packages/Twisted-16.7.0rc2-py2.7-linux-x86_64.egg/twisted/application/service.py", line 411, in loadApplication
passphrase)
File "/usr/local/lib/python2.7/dist-packages/Twisted-16.7.0rc2-py2.7-linux-x86_64.egg/twisted/persisted/sob.py", line 223, in loadValueFromFile
eval(codeObj, d, d)
File "launcher.tac", line 15, in 
import lib.settings as settings
exceptions.ImportError: No module named lib.settings

Failed to load application: No module named lib.settings
