### ISSUE TITLE
Log folder doesn't get created if doesn't exist

### ISSUE THREAD

**Issue by Neozonz** [moopless/stratum-mining-litecoin#6]
Create log folder if doesn't exist

BACKTRACK
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/application/app.py", line 652, in run
    runApp(config)
  File "/usr/lib/python2.7/dist-packages/twisted/scripts/twistd.py", line 23, in runApp
    _SomeApplicationRunner(config).run()
  File "/usr/lib/python2.7/dist-packages/twisted/application/app.py", line 386, in run
    self.application = self.createOrGetApplication()
  File "/usr/lib/python2.7/dist-packages/twisted/application/app.py", line 451, in createOrGetApplication
    application = getApplication(self.config, passphrase)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/application/app.py", line 462, in getApplication
    application = service.loadApplication(filename, style, passphrase)
  File "/usr/lib/python2.7/dist-packages/twisted/application/service.py", line 405, in loadApplication
    application = sob.loadValueFromFile(filename, 'application', passphrase)
  File "/usr/lib/python2.7/dist-packages/twisted/persisted/sob.py", line 210, in loadValueFromFile
    exec fileObj in d, d
  File "launcher.tac", line 16, in <module>
    application = stratum.setup(on_startup)
  File "/usr/local/lib/python2.7/dist-packages/stratum-0.2.12-py2.7.egg/stratum/server.py", line 24, in setup
    import stratum.example_service
  File "/usr/local/lib/python2.7/dist-packages/stratum-0.2.12-py2.7.egg/stratum/example_service.py", line 10, in <module>
    import logger
  File "/usr/local/lib/python2.7/dist-packages/stratum-0.2.12-py2.7.egg/stratum/logger.py", line 45, in <module>
    file_handler = logging.FileHandler(os.path.join(settings.LOGDIR, settings.LOGFILE))
  File "/usr/lib/python2.7/logging/__init__.py", line 897, in **init**
    StreamHandler.**init**(self, self._open())
  File "/usr/lib/python2.7/logging/__init__.py", line 916, in _open
    stream = open(self.baseFilename, self.mode)
exceptions.IOError: [Errno 2] No such file or directory: '/home/stratum-mining-litecoin/log/stratum.log'

Failed to load application: [Errno 2] No such file or directory: '/home/stratum-mining-litecoin/log/stratum.log'

**Comment by moopless** [comment]
The log directory is automatically created after c7c63e4b46315f1449a99443656fc2b229264486
