### ISSUE TITLE
Error In Log File ( if isinstance(e[2], str): exceptions.IndexError: tuple index out of range)

### ISSUE THREAD

**Issue by markudevelop** [moopless/stratum-mining-litecoin#67]
Hello, I wanted to ask for some help with the following error in log file. After running stratum-mining-litecoin I get starting litecoind... and nothing else (Trying to connect to Feathercoind)

2013-11-09 20:23:19+0100 [-] Log opened.
2013-11-09 20:23:19+0100 [-] twistd 12.0.0 (/usr/bin/python 2.7.3) starting up.
2013-11-09 20:23:19+0100 [-] reactor class: twisted.internet.epollreactor.EPollReactor.
2013-11-09 20:24:20+0100 [HTTPPageGetter,client] Unhandled error in Deferred:
2013-11-09 20:24:20+0100 [HTTPPageGetter,client] Unhandled Error
        Traceback (most recent call last):
          File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 397, in errback
            self._startRunCallbacks(fail)
          File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 464, in _startRunCallbacks
            self._runCallbacks()
          File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 551, in _runCallbacks
            current.result = callback(current.result, _args, *_kw)
          File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1101, in gotResult
            _inlineCallbacks(r, g, deferred)
        --- <exception caught here> ---
          File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1043, in _inlineCallbacks
            result = result.throwExceptionIntoGenerator(g)
          File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 382, in throwExceptionIntoGenerator
            return g.throw(self.type, self.value, self.tb)
          File "/root/stratum-mining-litecoin/mining/__init__.py", line 55, in setup
            if isinstance(e[2], str):
        exceptions.IndexError: tuple index out of range

2013-11-09 20:26:20+0100 [-] SIGINT Detected, shutting down
2013-11-09 20:26:20+0100 [-] Main loop terminated.
2013-11-09 20:26:20+0100 [-] Server Shut Down.

Any ideas what's wrong? Thanks a lot!

**Comment by obigal** [comment]
I've seen this before, it's usually an error / typo in your config file, I suggest creating a new one.

**Comment by markudevelop** [comment]
@obigal Thank you it worked!

**Comment by rabbie** [comment]
Hi,
I'm having this exact same issue and have replaced the config file, updated only the minimum requirements but I am still getting the same error.

Any ideas ?

```
2013-12-09 00:24:38+1100 [HTTPPageGetter,client] Unhandled error in Deferred:
2013-12-09 00:24:38+1100 [HTTPPageGetter,client] Unhandled Error
        Traceback (most recent call last):
          File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 397, in errback
            self._startRunCallbacks(fail)
          File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 464, in _startRunCallbacks
            self._runCallbacks()
          File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 551, in _runCallbacks
            current.result = callback(current.result, *args, **kw)
          File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1101, in gotResult
            _inlineCallbacks(r, g, deferred)
        --- <exception caught here> ---
          File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1043, in _inlineCallbacks
            result = result.throwExceptionIntoGenerator(g)
          File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 382, in throwExceptionIntoGenerator
            return g.throw(self.type, self.value, self.tb)
          File "/opt/stratum-mining-litecoin/mining/__init__.py", line 55, in setup
            if isinstance(e[2], str):
        exceptions.IndexError: tuple index out of range
```

**Comment by Jackster** [comment]
Also getting this error.

Trying to use it with DogeCoins if that makes a difference?

**Comment by AxelWal** [comment]
This Error happens when the RPC Connection fails.

**Comment by baitnfatty** [comment]
2014-01-17 03:57:20+0000 [-] Log opened.
2014-01-17 03:57:20+0000 [-] twistd 11.1.0 ( 2.7.3) starting up.
2014-01-17 03:57:20+0000 [-] reactor class: twisted.internet.epollreactor.EPollReactor.
2014-01-17 03:57:20+0000 [HTTPPageGetter,client] Unhandled error in Deferred:
2014-01-17 03:57:20+0000 [HTTPPageGetter,client] Unhandled Error
        Traceback (most recent call last):
          File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 391, in errback
            self._startRunCallbacks(fail)
          File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 458, in _startRunCallbacks
            self._runCallbacks()
          File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 545, in _runCallbacks
            current.result = callback(current.result, _args, *_kw)
          File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1095, in gotResult
            _inlineCallbacks(r, g, deferred)
        --- <exception caught here> ---
          File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1037, in _inlineCallbacks
            result = result.throwExceptionIntoGenerator(g)
          File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 382, in throwExceptionIntoGenerator
            return g.throw(self.type, self.value, self.tb)
          File "/root/stratum-mining/mining/__init__.py", line 68, in setup
            if isinstance(e[2], str):
        exceptions.IndexError: tuple index out of range

@rabbie I need the two lines above that error XD what version of twisted are you using? See above error. 

I am also having this issue. http://pastebin.com/PinSLnW4  <-configs
