### ISSUE TITLE
 'module' object has no attribute 'setup'

### ISSUE THREAD

**Issue by cybercorey** [moopless/stratum-mining-litecoin#70]
Running Ubuntu, this error has gotten the best of me, any ideas?

~/MiningPool/stratum-mining-litecoin# sudo twistd -y launcher.tac
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/application/app.py", line 652, in run
    runApp(config)
  File "/usr/lib/python2.7/dist-packages/twisted/scripts/twistd.py", line 23, in runApp
    _SomeApplicationRunner(config).run()
  File "/usr/lib/python2.7/dist-packages/twisted/application/app.py", line 386, in run
    self.application = self.createOrGetApplication()
  File "/usr/lib/python2.7/dist-packages/twisted/application/app.py", line 451, in createOrGetApplication
    application = getApplication(self.config, passphrase)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/application/app.py", line 462, in getApplication
    application = service.loadApplication(filename, style, passphrase)
  File "/usr/lib/python2.7/dist-packages/twisted/application/service.py", line 405, in loadApplication
    application = sob.loadValueFromFile(filename, 'application', passphrase)
  File "/usr/lib/python2.7/dist-packages/twisted/persisted/sob.py", line 210, in loadValueFromFile
    exec fileObj in d, d
  File "launcher.tac", line 22, in <module>
    application = stratum.setup(on_startup)
exceptions.AttributeError: 'module' object has no attribute 'setup'

Failed to load application: 'module' object has no attribute 'setup'

**Comment by zaibon** [comment]
I have the same error
running sabayon linux

**Comment by cybercorey** [comment]
https://github.com/ahmedbodi/stratum-mining/wiki/Getting-Started-With-Stratum worked like a charm for me
