### ISSUE TITLE
Trace back error

### ISSUE THREAD

**Issue by obigal** [moopless/stratum-mining-litecoin#8]
Looks like we still need the websocket=none in the config file or else I get this error upon startup, I just put all 4 back for good measure

---

.# Port used for HTTP Poll transport. Use 'None' for disabling the transport
LISTEN_HTTP_TRANSPORT = None
.# Port used for HTTPS Poll transport
LISTEN_HTTPS_TRANSPORT = None
.# Port used for WebSocket transport, 'None' for disabling WS
LISTEN_WS_TRANSPORT = None
.# Port used for secure WebSocket, 'None' for disabling WSS
LISTEN_WSS_TRANSPORT = None

---

2013-06-09 19:07:55-0400 [HTTPPageGetter,client] Starting WS transport on 8002
2013-06-09 19:07:55-0400 [HTTPPageGetter,client] Unhandled error in Deferred:
2013-06-09 19:07:55-0400 [HTTPPageGetter,client] Unhandled Error
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1071, in _inlineCallbacks
        result = g.send(result)
      File "/home/bigal/stratum-test/mining/__init__.py", line 88, in setup
        on_startup.callback(True)
      File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 381, in callback
        self._startRunCallbacks(result)
      File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 489, in _startRunCallbacks
        self._runCallbacks()
    --- <exception caught here> ---
      File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 576, in _runCallbacks
        current.result = callback(current.result, _args, *_kw)
      File "/usr/local/lib/python2.7/dist-packages/stratum-0.2.12-py2.7.egg/stratum/server.py", line 101, in setup_finalize
        tcp_proxy_protocol_enable=settings.TCP_PROXY_PROTOCOL)
    exceptions.TypeError: __init__() got an unexpected keyword argument 'tcp_proxy_protocol_enable'

**Comment by moopless** [comment]
Nice catch. Looks like stratum-0.2.12-py2.7.egg/stratum/config_default.py has those values set, so we do need to disable them.  Should be resolved in 70a9d7a645f1e77f68b3a33c25a5b9c0f7a814b2
