### ISSUE TITLE
Error with HoboNickels 

### ISSUE THREAD

**Issue by techwebhosting** [moopless/stratum-mining-litecoin#86]
I seem to be getting the following error when working with HoboNickels. 

2013-12-29 14:43:36,736 ERROR template_registry # [Failure instance: Traceback: <class 'struct.error'>: unpack requires a string argument of length 4

I am assuming it has something to do with the block template, but I am not 100% sure. 

Any help\guidance would be appreciated.

**Comment by astalavister** [comment]
Have you set key instead of simple wallet address in config? as i remember for HBN it must be so.

**Comment by techwebhosting** [comment]
Yes and when doing so it complains that the address isn't valid. The pub key is supposed to go in the same spot correct?

DJ Anderson
Sent from my iPhone

On Dec 29, 2013, at 3:37 PM, "astalavister" <notifications@github.com<mailto:notifications@github.com>> wrote:

Have you set key instead of simple wallet address in config? as i remember for HBN it must be so.

**Comment by astalavister** [comment]
Cant see now, havent working hbn wallet near.
But from configs - it must be like so:
#CENTRAL_WALLET = 'EnEcVj6txZ1tkTfrct77fzrKdJ4zdk1hbs'  # local litecoin address where money goes
CENTRAL_WALLET = '02b7fdfce6543bf7ab389875f0ed1c65d712dad6985d5f0bf700045720ae7d98ef'
There are some command on wallet which is generated that key.

**Comment by techwebhosting** [comment]
Thanks for the help so far.

That is the way that I did it.

When I start it with those settings I get the following error.

ERROR coinbaser # Wallet address ‘addressremovedforsafety' is NOT valid!
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Twisted-13.2.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 1099, in _inlineCallbacks
    result = g.send(result)
  File "/home/username/stratum-mining/lib/bitcoin_rpc.py", line 88, in validateaddress
    defer.returnValue(json.loads(resp)['result'])
  File "/usr/local/lib/python2.7/dist-packages/Twisted-13.2.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 1076, in returnValue
    raise _DefGen_Return(val)
_DefGen_Return

**Comment by techwebhosting** [comment]
Any word on this? 

I have been tinkering around and I really haven't found a solution yet.

**Comment by astalavister** [comment]
look for ahmedbodi git, will get rid of most problems with this stratum :)

**Comment by TheSerapher** [comment]
https://github.com/ahmedbodi/stratum-mining
