### ISSUE TITLE
stratum mining issue with lottocoin

### ISSUE THREAD

**Issue by shanetk** [moopless/stratum-mining-litecoin#96]
Hi,

 I am getting the below error while setting up lottocoin with stratum-mining. Can you please help me on this why this error happens.

++++++++
2014-03-30 04:40:40+0000 [HTTPPageGetter,client] Unhandled error in Deferred:
2014-03-30 04:40:40+0000 [HTTPPageGetter,client] Unhandled Error
        Traceback (most recent call last):
          File "/usr/local/lib/python2.7/dist-packages/Twisted-13.2.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 1099, in _inlineCallbacks
            result = g.send(result)
          File "/usr/local/src/stratum-mining/mining/__init__.py", line 127, in setup
            on_startup.callback(True)
          File "/usr/local/lib/python2.7/dist-packages/Twisted-13.2.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 382, in callback
            self._startRunCallbacks(result)
          File "/usr/local/lib/python2.7/dist-packages/Twisted-13.2.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 490, in _startRunCallbacks
            self._runCallbacks()
        --- <exception caught here> ---
          File "/usr/local/lib/python2.7/dist-packages/Twisted-13.2.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 577, in _runCallbacks
            current.result = callback(current.result, _args, *_kw)
          File "/usr/local/lib/python2.7/dist-packages/stratum-0.2.13-py2.7.egg/stratum/server.py", line 77, in setup_finalize
            socket.setServiceParent(application)
          File "/usr/local/lib/python2.7/dist-packages/Twisted-13.2.0-py2.7-linux-x86_64.egg/twisted/application/service.py", line 186, in setServiceParent
            self.parent.addService(self)
          File "/usr/local/lib/python2.7/dist-packages/Twisted-13.2.0-py2.7-linux-x86_64.egg/twisted/application/service.py", line 308, in addService
            service.privilegedStartService()
          File "/usr/local/lib/python2.7/dist-packages/Twisted-13.2.0-py2.7-linux-x86_64.egg/twisted/application/internet.py", line 105, in privilegedStartService
            self._port = self._getPort()
          File "/usr/local/lib/python2.7/dist-packages/Twisted-13.2.0-py2.7-linux-x86_64.egg/twisted/application/internet.py", line 133, in _getPort
            'listen%s' % (self.method,))(_self.args, *_self.kwargs)
          File "/usr/local/lib/python2.7/dist-packages/Twisted-13.2.0-py2.7-linux-x86_64.egg/twisted/internet/posixbase.py", line 495, in listenTCP
            p.startListening()
          File "/usr/local/lib/python2.7/dist-packages/Twisted-13.2.0-py2.7-linux-x86_64.egg/twisted/internet/tcp.py", line 978, in startListening
            skt.bind(addr)
          File "/usr/lib/python2.7/socket.py", line 224, in meth
            return getattr(self._sock,name)(*args)
        exceptions.TypeError: an integer is required
++++++++++++++

I have used the repository https://github.com/ahmedbodi/stratum-mining.git. Please help me as I am stuck here.

**Comment by shanetk** [comment]
Hi,

 Can any one please help.
